service: sls-py-req-test

provider:
  name: aws
  runtime: python3.6

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    zip: false
    cleanupZipHelper: true
    dockerizePip: false
    prereqCmd: null

package:
  exclude:
    - '**/*'
  include:
    - handler.py

functions:
  hello:
    handler: handler.hello
