version: 2
jobs:
  build:
    working_directory: ~/sls-py-req
    machine:
      image: circleci/python:3.6.5
    steps:
      - checkout
      # other deps
      - run: sudo apt -y update && sudo apt -y install python-pip python2.7 curl unzip
      # upgrade python3.6 pip to latest
      - run: sudo python3.6 -m pip install -U pip
      # instal pipenv
      - run: sudo python3.6 -m pip install pipenv pip-tools
      # install poetry
      - run: |
          curl https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py -o get-poetry.py
          python get-poetry.py --preview --yes
          rm get-poetry.py
      # install serverless & depcheck
      - run: npm install -g serverless
      # install deps
      - run: npm i
      # lint:
      - run: npm run ci:lint
      # test!
      - run: |
          export PATH="$HOME/.poetry/bin:$PATH"
          export LC_ALL=C.UTF-8
          export LANG=C.UTF-8
          npm run test
      - store_test_results:
          path: ~/reports
      - store_artifacts:
          path: ~/reports
